gfarm-s3-subr: define log_debug, log_info, ...

diff --git a/bin/gfarm-s3-subr b/bin/gfarm-s3-subr
--- a/bin/gfarm-s3-subr
+++ b/bin/gfarm-s3-subr
@@ -1,6 +1,120 @@
 # -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
 
 #################################################
+### loggin
+#################################################
+
+_log_level_to_num() {
+    LEVEL="$1"
+    case $LEVEL in
+        debug)
+            echo 0
+            ;;
+        info)
+            echo 1
+            ;;
+        notice)
+            echo 2
+            ;;
+        warning)
+            echo 3
+            ;;
+        err)
+            echo 4
+            ;;
+        crit)
+            echo 5
+            ;;
+        alert)
+            echo 6
+            ;;
+        emerg)
+            echo 7
+            ;;
+        *)
+            echo 4
+            ;;
+    esac
+}
+
+_LOG_INITIALIZED=0
+_NO_DEVLOG=0
+
+_log_init() {
+    [ $_LOG_INITIALIZED -eq 1 ] && return
+
+    DEVLOG="/dev/log"
+    if [ ! -e $DEVLOG ]; then
+        _NO_DEVLOG=1
+    fi
+    _LOG_INITIALIZED=1
+}
+
+_log_common() {
+    LEVEL="$1"
+    MSG="$2"
+
+    CONF_LEVEL_NUM=$(_log_level_to_num "$GFARM_S3_LOG_LEVEL")
+    MSG_LOG_LEVEL_NUM=$(_log_level_to_num "$LEVEL")
+
+    if [ $MSG_LOG_LEVEL_NUM -lt $CONF_LEVEL_NUM ]; then
+        return
+    fi
+
+    TAG=$(basename $0)
+    LEVEL_UPPER=$(echo ${LEVEL} | tr [:lower:] [:upper:])
+    _log_init
+
+    STDERR=0
+    SYSLOG=0
+    case $GFARM_S3_LOG_OUTPUT in
+        *syslog*)
+            if [ ${_NO_DEVLOG} -ne 1 ]; then
+                SYSLOG=1
+            fi
+            ;;
+    esac
+    case $GFARM_S3_LOG_OUTPUT in
+        *stderr*)
+            STDERR=1
+            ;;
+    esac
+    if [ ${SYSLOG} -eq 0 -a ${STDERR} -eq 0 ]; then
+        STDERR=1
+    fi
+
+    if [ ${STDERR} -eq 1 ]; then
+        echo "[${TAG}] ${LEVEL_UPPER}: ${MSG}" >&2
+    fi
+
+    if [ ${SYSLOG} -eq 1 ]; then
+        logger -i -t $TAG -p "${GFARM_S3_LOG_FACIRITY}.${LEVEL}" \
+               "${LEVEL_UPPER}: ${MSG}"
+    fi
+}
+
+log_debug() {
+    _log_common "debug" "$1"
+}
+
+log_info() {
+    _log_common "info" "$1"
+}
+
+log_notice() {
+    _log_common "notice" "$1"
+}
+
+log_warning() {
+    _log_common "warning" "$1"
+}
+
+log_err() {
+    _log_common "err" "$1"
+}
+
+
+#################################################
 ### utilities & common subroutines
 #################################################
 
@@ -318,7 +432,7 @@ configtest_local_user_exisence_test() {
 configtest_all() {
 	local status=0
 
-	echo configtest_all: 1>&2
+	#echo configtest_all: 1>&2
 	#sed 's/^/> /' "$1" 1>&2
 
 	if ! configtest_format_test "$1"; then return 1; fi
@@ -328,7 +442,7 @@ configtest_all() {
 	if ! configtest_local_username_test "$1"; then status=1; fi
 	if ! configtest_access_key_test "$1"; then status=1; fi
 	if ! configtest_local_user_exisence_test "$1"; then status=1; fi
-	echo status=$status 1>&2
+	#echo status=$status 1>&2
 	return $status
 }
 
@@ -341,7 +455,7 @@ update_usermap() {
 			rm -f "$tmpfile"
 			return 1
 		fi
-		if cmp "$GFARMS3_LOCAL_USER_MAP" "$tmpfile" >/dev/null; then
+		if cmp -s "$GFARMS3_LOCAL_USER_MAP" "$tmpfile"; then
 			echo no edit 1>&2
 			echo "update_usermap: $GFARMS3_LOCAL_USER_MAP: unchanged" 1>&2
 			rm -f "$tmpfile"
@@ -494,13 +608,13 @@ challenge_auth() {
 			-o "$x509_user_proxy" \
 			${PROXY_LIFETIME:+-t "$PROXY_LIFETIME"} 2>&1)
 		if [ $? = 0 ]; then
-			echo SUCCESS $MYPROXY_LOGON 1>&2
-			logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "myproxy-logon: $local_user SUCCESS $res"
-			echo myproxy-logon
+			#echo SUCCESS $MYPROXY_LOGON 1>&2
+			log_debug "myproxy-logon: $local_user SUCCESS $res"
+			echo myproxy-logon  # result
 			return 0
 		else
 			echo FAIL $MYPROXY_LOGON 1>&2
-			logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "myproxy-logon: $local_user FAIL $res"
+			log_debug "myproxy-logon: $local_user FAIL $res"
 		fi
 		;;
 	esac
@@ -510,20 +624,20 @@ challenge_auth() {
 	*grid-proxy-init*)
 		if check_nopasswd "$local_user"; then
 			echo SKIP $GRID_PROXY_INIT 1>&2
-			logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "grid-proxy-init: $local_user SKIP"
+			log_debug "grid-proxy-init: $local_user SKIP"
 		else
 			res=$(echo "$user_provided_key" |
 				mysudo "$local_user" $GRID_PROXY_INIT \
 				-out "$x509_user_proxy" \
 				-pwstdin 2>&1)
 			if [ $? = 0 ]; then
-				echo SUCCESS $GRID_PROXY_INIT 1>&2
-				logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "grid-proxy-init: $local_user SUCCESS $res"
-				echo grid-proxy-init
+				#echo SUCCESS $GRID_PROXY_INIT 1>&2
+				log_debug "grid-proxy-init: $local_user SUCCESS $res"
+				echo grid-proxy-init  # result
 				return 0
 			else
-				echo FAIL $GRID_PROXY_INIT 1>&2
-				logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "grid-proxy-init: $local_user FAIL $res"
+				#echo FAIL $GRID_PROXY_INIT 1>&2
+				log_debug "grid-proxy-init: $local_user FAIL $res"
 			fi
 		fi
 		;;
@@ -536,17 +650,18 @@ challenge_auth() {
 		res=$(cat $tmpfile)
 		rm $tmpfile
 		if [ "$user_provided_key" = "$user_key" ]; then
-			echo SUCCESS gfkey digest 1>&2
-			logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "gfarm-shared-key: $local_user SUCCESS $res"
-			echo gfkey
+			#echo SUCCESS gfkey digest 1>&2
+			log_debug "gfarm-shared-key: $local_user SUCCESS $res"
+			echo gfkey  # result
 			return 0
 		else
-			echo FAIL gfkey digest 1>&2
-			logger -i -p local7.debug -t gfarm-s3-minio-web:challenge_auth "gfarm-shared-key: $local_user FAIL $res"
+			#echo FAIL gfkey digest 1>&2
+			log_debug "gfarm-shared-key: $local_user FAIL $res"
 		fi
 		;;
 	esac
 
+        # Error
 	sleep 5
 	return 1
 }
@@ -574,11 +689,11 @@ spawn_per_user_server_common() {
 	local status=0
 
 	if [ "$port_pid" = "$NOT_STARTED" ]; then
-		echo "MinIO (for $user) is not enabled" 1>&2
+		log_info "MinIO (for $user) is not enabled"
 	elif [ -n "$port_pid" ]; then
 		local port="${port_pid%:*}"
 		local pid="${port_pid#*:}"
-		echo "MinIO started (for $user)" 1>&2
+		log_info "MinIO started (for $user)"
 		## No need to check `port' confliction,
 		## as a port # that returned by gfarm-s3-server is
 		## actually allocated for current user.
@@ -589,7 +704,7 @@ spawn_per_user_server_common() {
 			status=2
 		fi
 	else
-		echo "ERROR: MinIO could not start" 1>&2
+		log_warning "MinIO could not start"
 	fi
 	return $status
 }
@@ -790,7 +905,7 @@ update_reverse_proxy_for_apache() {
 	fi
 
 	if cmp -s "$tmpfile" "$GFARMS3_APACHE_REWRITE_CONF"; then
-		echo "no change" 1>&2
+		#echo "no change" 1>&2
 		rm "$tmpfile"
 	else
 		mv "$tmpfile" "$GFARMS3_APACHE_REWRITE_CONF"
@@ -810,7 +925,7 @@ update_reverse_proxy_for_router() {
 	fi
 
 	if cmp -s "$tmpfile" "$GFARMS3_REVERSE_PROXY_ROUTES"; then
-		echo "no change" 1>&2
+		#echo "no change" 1>&2
 		rm "$tmpfile"
 	else
 		chmod og+r "$tmpfile"
@@ -857,7 +972,7 @@ _mc() {
         status=1
     fi
     _mc_fin "$config_dir"
-    logger -i -p local7.debug -t gfarm-s3-minio-web:mc "[$r]"
+    log_debug "mc: {$r}"
     return $status
 }
 
@@ -950,7 +1065,7 @@ try_start_a_server() {
 	if minio_connect_check $address; then
 		## MinIO is already running
 		## success with empty stdout
-		logger -i -p local7.debug -t gfarm-s3-minio-web:try_start_a_server "[S] minio is already running"
+		log_debug "try_start_a_server: [S] minio is already running"
 		return $SUCCESS
 	fi
 	local tmpfile=$(mktemp $GFARM_S3_TMP/minio-log.XXXXXX) || return $ABORT
@@ -972,7 +1087,7 @@ try_start_a_server() {
 	 echo "Minio Exited") <&- >$tmpfile 2>&1 3>$pidfile &
 	RETRY_MAX=60  # sec.
 	for i in $(seq 1 1 $RETRY_MAX); do
-		if egrep "^(Endpoint|Minio Exited)" $tmpfile 1>&2; then
+		if egrep -q "^(Endpoint|Minio Exited)" $tmpfile 1>&2; then
 			## MinIO started, and wrote greeting message to stdout
 			## or MinIO exited (for some reason)
 			break
@@ -981,7 +1096,7 @@ try_start_a_server() {
 	done
 
 	# debug
-	cat $tmpfile 1>&2
+	#cat $tmpfile 1>&2
 
 	local port_pid=$(cat $pidfile)
 	#port="${port_pid%:*}"
@@ -1009,7 +1124,7 @@ try_start_a_server() {
 		if ! grep -l "port is already in use" $tmpfile 1>&2; then
 			rm -f $tmpfile
 ###			case 2
-			logger -i -p local7.debug -t gfarm-s3-minio-web:try_start_a_server "[2] port is in use"
+			log_debug "try_start_a_server: [2] port is in use"
 			return $ABORT
 		fi
 
@@ -1018,11 +1133,11 @@ try_start_a_server() {
 		return $RETRY	## temporary error (minio has quit)
 	fi
 
-	if ! grep -l "^Endpoint" $tmpfile 1>&2; then
+	if ! grep -q -l "^Endpoint" $tmpfile 1>&2; then
 		kill -KILL $pid
 		rm -f $tmpfile
 ###		case 3
-		logger -i -p local7.debug -t gfarm-s3-minio-web:try_start_a_server "[3] fatal error (another minio may running)"
+		log_debug "try_start_a_server: [3] fatal error (another minio may running)"
 		return $ABORT	## fatal error (minio may still running)
 	fi
 
@@ -1032,11 +1147,11 @@ try_start_a_server() {
 	if ! minio_connect_check $address; then
 		kill -KILL $pid
 ###		case 0 => case 4
-		logger -i -p local7.debug -t gfarm-s3-minio-web:try_start_a_server "[4] error (another minio is running, or Gfarm authentication is failed)"
+		log_debug "try_start_a_server: [4] error (another minio is running, or Gfarm authentication is failed)"
 		return $ABORT
 	fi
 	echo "$port:$pid"  # result
-	logger -i -p local7.debug -t gfarm-s3-minio-web:try_start_a_server "[5] minio started"
+	log_debug "try_start_a_server: [5] minio started"
 ###	case 0 => case 5:
 	return $SUCCESS
 }
@@ -1049,6 +1164,7 @@ stop_server() {
 		return 1
 	fi
 	try_stop_a_server "$port" "$pid"
+        log_info "MinIO stopped (for $USER)"
 	save_started_status 0 "$USER"
 }
 
@@ -1059,7 +1175,7 @@ try_stop_a_server() {
 	if minio_connect_check $address; then
 		if minio_stop; then
 			for i in $(seq 1 1 $GFARM_S3_WAIT_COUNT); do
-				if ! kill -0 $pid; then
+				if ! kill -0 $pid >/dev/null 2>&1; then
 					return 0
 				fi
 				sleep 1
@@ -1068,13 +1184,13 @@ try_stop_a_server() {
 		fi
 	fi
 	for i in $(seq 1 1 $GFARM_S3_KILL_COUNT); do
-		if ! kill -0 $pid; then
+		if ! kill -0 $pid >/dev/null 2>&1; then
 			return 0
 		fi
-		kill -TERM $pid
+		kill -TERM $pid >/dev/null 2>&1 || true
 		sleep 1
 	done
-	kill -KILL $pid
+	kill -KILL $pid >/dev/null 2>&1
 	return 0
 }
 
